language: go
go_import_path: github.com/mailchain/mailchain
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
dist: xenial
before_install:
  - go get github.com/mattn/goveralls
install: true
script:
  - make build
  - make unit-test
  - $GOPATH/bin/goveralls -service=travis-ci
