language: go
go_import_path: github.com/mailchain/mailchain
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
dist: xenial
before_install:
  - go get github.com/mattn/goveralls
install: true
script:
  - make build
  - make unit-test
  - go test -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
deploy:
  - provider: script
    script: docker run --rm --privileged -v $TRAVIS_BUILD_DIR -v /var/run/docker.sock:/var/run/docker.sock -w $TRAVIS_BUILD_DIR mailchain/goreleaser-xcgo goreleaser --rm-dist
    on:
      tags: true
      branch: master
